### PR TITLE
Add support for WPML

### PR DESCRIPTION
**Pull request by vincentducorps**

### CODE REVIEW

**Comment by JayWood** [comment]
@vincentducorps wow thanks, would you care to elaborate on what the XML is for? Maybe a link to the WPML documentation?

**Comment by vincentducorps** [comment]
Sure : https://wpml.org/documentation/support/language-configuration-files/

With this file, you can translate "options" with WPML String Translation.

Thank to you for this plugin

**Comment by JayWood** [comment]
@vincentducorps Sounds good, thanks, I'll merge this into dev and put it in the next update.

**Comment by ngoctam1011** [comment]
How to add multi languages into this plugin?

**Comment by JayWood** [comment]
@ngoctam1011 I'm working on setting it up for localization, will be providing a file in next release which you can of course feel free to translate.

**Comment by ngoctam1011** [comment]
Would yo please send me the demo and I am willing to test it.

**Pull request merged**
